### ISSUE TITLE
[Feature request] Perpending and appending string

### ISSUE THREAD

**Issue by alessandrodallafina** [LeonardPauli/LayerRenamer#1]
First of all, awesome plugin! I looove ti! 

Just a small side note. Not sure how hard would it be supporting the prepending/appending feature. This way users can keep the layer name and simply appending other strings without affecting the original values. 

Just a thought ;)

**Comment by leonardpauli** [comment]
Haha, thanks! Of course it's supported! Just put parenthesis around your find expression (it's regular expressions after all) and then `prefix$1suffix` as the replacement! With regex, you can even do a lot more powerful things! Try pressing the help-button (?) in the corner of the dialog :)

Examples:
Find: `stone` (anywhere, case-insensitive, in the name)
Replace: `flower`
With the layers with the following names selected
`hello stone` -> `hello flower`
`hello tree` -> `hello tree` (no match)
`thestonemaster` -> `theflowermaster`

Find: `^stone$` (exactly, case-insensitive, `^` is the start, `$` is the end)
Replace: `flower`
With the layers with the following names selected
`hello stone` -> `hello stone` (no match)
`stone` -> `flower`

Find: `(.+)` (anything, and save it as `$1`, same as just leaving the field empty)
Replace: `A $1 heh`
With the layers with the following names selected
`hello stone` -> `A hello stone heh`
`stone` -> `A stone heh`

Find: `^(flower)( ?copy( \d)?)+` (more complex regex)
Replace: `A $1, %N`
With the layers with the following names selected, in that order
`flower` -> `flower` (No match - doesn't have "copy"...)
`flower copy 3` -> `A flower, 1` (first match)
`stone flower copy 1` -> `stone flower copy 1` (No mach - doesn't start with "flower")
`flower copy 3 copy 5` -> `A flower, 2` (second match)
`flower copy 1 copy` -> `A flower, 3` (third match)

**Comment by leonardpauli** [comment]
So basically, just:
- Select your layers (alternatively find them through the included Select plugin; `cmd-alt-F`)
- Hit `cmd-alt-R`
- Leave the first field empty (ie. hit `backspace` followed by `tab`)
- Write `my prefix $1 my suffix` (`$1` is the original layer name)
- Hit enter

**Comment by alessandrodallafina** [comment]
Damn it, I took a look at some of the things that you can do with RegEx but I totally missed it! #facepalm 

Thanks a lot for replying so quickly! And keep it up!

**Comment by printly** [comment]
Is it possible to change a case of character?
for example, it's possible to do it as [described here](http://stackoverflow.com/questions/1159343/convert-a-char-to-upper-case-using-regular-expressions-editpad-pro), but I can't achieve this in your plugin.

e.g. if I want to modify
test sentence -> Test sentence
in sublime text editor I can do it this way:
Find what:
\b(\w)()
Replace with:
\U$1

But this trick doesn't seem to be worked in your plugin...

it rename layer test sentence
to \Utest sentence
instead of making first letter uppercase

Thank you in advance!
