### ISSUE TITLE
[Feature request] Rename group after first child layer

### ISSUE THREAD

**Issue by Maikenvv** [LeonardPauli/LayerRenamer#6]
I would like to rename groups after a layer within them. Is it possible to add this?

**Comment by leonardpauli** [comment]
Ahh, interesting! Absolutely, although not sure how user-friendly it will be with a text-input only (would love to add custom UI later on, no time right now).

![rename group using inner layer name](https://user-images.githubusercontent.com/1329834/28284113-3945311c-6b30-11e7-9da6-69ba7ed978e4.gif)

Well, think I solved it :)

(Using the same principle as when navigating layer tree for selecting; `>` for children, `<` for parent, digits for layer index, etc, so `%>0` would be first child, to get its title; append `.t`. So `%>1>0.t` would be the name/title of the first layer in the second group inside the selected group...)

*"Added ability to rename group by its children layers (fixes #6) ie. put "%>0.t" (without quotes) in the replace-with-input-box to get first child name
Bumped version nr"*

**Comment by leonardpauli** [comment]
A more concrete use case I actually run into today;

![rename using children](https://user-images.githubusercontent.com/1329834/28329735-2acfe8fa-6beb-11e7-9666-55adfbd27d75.gif)

**Comment by Maikenvv** [comment]
The above example was exactly my problem. Thank you for adding this. This will save a lot of time working on projects and keeping everything in sync.
